Custom CA and certs; deployment scripts to pick-up certs from the ca directory

diff --git a/120-tomcat-configure b/120-tomcat-configure
--- a/120-tomcat-configure
+++ b/120-tomcat-configure
@@ -3,41 +3,38 @@
 . ./platform.properties
 . ./functions
 . ./functions-tomcat
+. ./ca/ca.properties
 
 #---------------------------------------------
-generateServerCert() {
+copyServerCert() {
 #---------------------------------------------
-  ${OPENSSL} genrsa -out ${TOMCAT_SERVER_KEY_PEM} 2048
-  if [ $? != 0 ]; then
-    printf "ERROR: Failed to generate server key.\n"
-    exitFailure
+
+  KEY_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-key-no-pin.pem
+  P12_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-key.p12
+  JKS_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-key.jks
+  CERT_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-cert.pem
+
+  if [ ! -f ${KEY_FILE} ]; then
+    printf "ERROR: Key file ${KEY_FILE} does not exist. You must create it first. Check the ca section.\n"
+    exit 1 
+  fi
+  if [ ! -f ${CERT_FILE} ]; then
+    printf "ERROR: Certificate file ${CERT_FILE} does not exist. You must create it first. Check the ca section.\n"
+    exit 1 
+  fi
+  if [ ! -f ${P12_FILE} ]; then
+    printf "ERROR: Key file ${P12_FILE} does not exist. You must create it first. Check the ca section.\n"
+    exit 1 
+  fi
+  if [ ! -f ${JKS_FILE} ]; then
+    printf "ERROR: Key file ${JKS_FILE} (Java Keystore) does not exist. You must create it first. Check the ca section.\n"
+    exit 1 
   fi
 
-  ${OPENSSL} req -new -x509 -key ${TOMCAT_SERVER_KEY_PEM} -out ${TOMCAT_SERVER_CERT_PEM} -days 3650 -subj "/CN=${SERVER_FQDN}" -sha256
-  if [ $? != 0 ]; then
-    printf "ERROR: Failed to generate self signed server certificate.\n"
-    exitFailure
-  fi
-
-  #Convert to .p12
-  ${OPENSSL} pkcs12 -export -in ${TOMCAT_SERVER_CERT_PEM} -inkey ${TOMCAT_SERVER_KEY_PEM} -out ${TOMCAT_SERVER_KEY_P12} -name ${SERVER_FQDN} -passout pass:${TOMCAT_SERVER_KEY_PIN}
-
-  #Generate Java Keystore and import key
-  if [ ! -f ${TOMCAT_KEYSTORE} ]; then
-    ${KEYTOOL} -genkey -alias foo -keystore ${TOMCAT_KEYSTORE} -storepass ${TOMCAT_KEYSTORE_STOREPASS} -dname cn=foo -keypass bogusbogus
-    ${KEYTOOL} -delete -alias foo -keystore ${TOMCAT_KEYSTORE} -storepass ${TOMCAT_KEYSTORE_STOREPASS}
-  fi
-
-  ${KEYTOOL} -importkeystore -srckeystore ${TOMCAT_SERVER_KEY_P12} -srcstoretype pkcs12 -srcalias ${SERVER_FQDN} -srcstorepass ${TOMCAT_SERVER_KEY_PIN} -destkeystore ${TOMCAT_KEYSTORE} -deststoretype jks -deststorepass ${TOMCAT_KEYSTORE_STOREPASS} -destalias ${SERVER_FQDN} -noprompt 
-  if [ $? != 0 ]; then
-    printf "WARNING: Failed to import server key into keystore at ${TOMCAT_KEYSTORE}.\n"
-    # exitFailure
-  fi
-
-  printf "INFO: Listing content of keystore ${TOMCAT_KEYSTORE}:\n"
-  ${KEYTOOL} -list -keystore ${TOMCAT_KEYSTORE} -storepass ${TOMCAT_KEYSTORE_STOREPASS}
-
-  printf "INFO: Successfully generated server key (${TOMCAT_SERVER_KEY_PEM}) and server certificate (${TOMCAT_SERVER_CERT_PEM}).\n"
+  ${CP} ${KEY_FILE} ${TOMCAT_SERVER_KEY_PEM}
+  ${CP} ${CERT_FILE} ${TOMCAT_SERVER_CERT_PEM}
+  ${CP} ${P12_FILE} ${TOMCAT_SERVER_KEY_P12}
+  ${CP} ${JKS_FILE} ${TOMCAT_KEYSTORE}
 }
 
 #---------------------------------------------
@@ -67,7 +64,7 @@ modifyTomcatConfig() {
 #---------------------------------------------
 # Main
 #---------------------------------------------
-generateServerCert
+copyServerCert
 modifyTomcatConfig
 stopTomcat
 startTomcat
diff --git a/220-httpd-configure b/220-httpd-configure
--- a/220-httpd-configure
+++ b/220-httpd-configure
@@ -3,37 +3,34 @@
 . ./platform.properties
 . ./functions
 . ./functions-httpd
+. ./ca/ca.properties
 
 #---------------------------------------------
-generateServerCert() {
+copyServerCert() {
 #---------------------------------------------
-  ${OPENSSL} genrsa -out ${HTTPD_SERVER_KEY_PEM} 2048
-  if [ $? != 0 ]; then
-    printf "ERROR: Failed to generate server key.\n"
-    exitFailure
+
+  KEY_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-key-no-pin.pem
+  P12_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-key.p12
+  CERT_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-cert.pem
+  CERT_CHAIN=${CA_SSL_SERVER_CERT_DIR}/../${CA_CERT}
+
+  if [ ! -f ${KEY_FILE} ]; then
+    printf "ERROR: Key file ${KEY_FILE} does not exist. You must create it first. Check the ca section.\n"
+    exit 1 
+  fi
+  if [ ! -f ${CERT_FILE} ]; then
+    printf "ERROR: Certificate file ${CERT_FILE} does not exist. You must create it first. Check the ca section.\n"
+    exit 1 
+  fi
+  if [ ! -f ${CERT_CHAIN} ]; then
+    printf "ERROR: Certificate chain file ${CERT_CHAIN} does not exist. Check the ca section.\n"
+    exit 1 
   fi
 
-  ${OPENSSL} req -new -x509 -key ${HTTPD_SERVER_KEY_PEM} -out ${HTTPD_SERVER_CERT_PEM} -days 3650 -subj "/CN=${SERVER_FQDN}" -sha256
-  if [ $? != 0 ]; then
-    printf "ERROR: Failed to generate self signed server certificate.\n"
-    exitFailure
-  fi
-
-  #Convert to .p12
-  ${OPENSSL} pkcs12 -export -in ${HTTPD_SERVER_CERT_PEM} -inkey ${HTTPD_SERVER_KEY_PEM} -out ${HTTPD_SERVER_KEY_P12} -name ${SERVER_FQDN} -passout pass:${HTTPD_SERVER_KEY_PIN}
-  if [ $? != 0 ]; then
-    printf "ERROR: Failed to generate self signed (HTTPD) server certificate.\n"
-    exitFailure
-  fi
-
-  printf "INFO: Successfully generated server key (${HTTPD_SERVER_KEY_PEM}) and server certificate (${HTTPD_SERVER_CERT_PEM}).\n"
-}
-
-#---------------------------------------------
-generateServerCertChain() {
-#---------------------------------------------
-  #${OPENSSL} verify -CAfile ${HTTPD_SERVER_CERT_CHAIN_PEM} ${HTTPD_SERVER_CERT_PEM}
-  cat ${HTTPD_SERVER_CERT_PEM} >> ${HTTPD_SERVER_CERT_CHAIN_PEM}
+  ${CP} ${KEY_FILE} ${HTTPD_SERVER_KEY_PEM}
+  ${CP} ${CERT_FILE} ${HTTPD_SERVER_CERT_PEM}
+  ${CP} ${P12_FILE} ${HTTPD_SERVER_KEY_P12}
+  ${CP} ${CERT_CHAIN} ${HTTPD_SERVER_CERT_CHAIN_PEM}
 }
 
 #---------------------------------------------
@@ -61,8 +58,7 @@ modifyHttpdConfig() {
 #---------------------------------------------
 # Main
 #---------------------------------------------
-generateServerCert
-generateServerCertChain
+copyServerCert
 modifyHttpdConfig
 stopHttpd
 startHttpd
