Move ssoadm batch and status file to tnp directory

diff --git a/410-openam-install b/410-openam-install
--- a/410-openam-install
+++ b/410-openam-install
@@ -27,6 +27,14 @@ installOpenAM() {
     fi
   fi
 
+  if [ ! -d ${TMP_BASE} ]; then
+    ${MKDIR} ${TMP_BASE}
+    if [ $? != 0 ]; then
+      printf "ERROR: Error creating the temp file directory ${TMP_BASE}. Aborting.\n"
+      exitFailure
+    fi
+  fi
+
   #
   # Extract the MEGA Zip
   #
