Still tinkering, configure realm and persistent cookie authentication module and class

diff --git a/480-openam-check b/480-openam-check
--- a/480-openam-check
+++ b/480-openam-check
@@ -18,6 +18,31 @@ checkSsoadm() {
 }
 
 #---------------------------------------------
+checkRestAuth() {
+#---------------------------------------------
+  REST_AUTH_URL=https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/authenticate
+
+  printf "INFO: Authentication via REST check as user demo ...\n"
+  ${CURL} --insecure --request POST --header "X-OpenAM-Username: demo" --header "X-OpenAM-Password: wrongchangeit" --header "Content-Type: application/json" --data "{}" ${REST_AUTH_URL}
+  printf "\n"
+  if [ $? != 0 ]; then
+    printf "ERROR: Error authenticating as user demo via REST.\n"
+  else
+    printf "INFO: Successfully authenicated as user demo via REST.\n"
+  fi
+
+  printf "INFO: Authentication via REST check as user ${OPENAM_ADMIN} ...\n"
+  ${CURL} --insecure --request POST --header "X-OpenAM-Username: ${OPENAM_ADMIN}" --header "X-OpenAM-Password: ${OPENAM_ADMIN_PASSWORD}" --header "Content-Type: application/json" --data "{}" ${REST_AUTH_URL}
+  printf "\n"
+  if [ $? != 0 ]; then
+    printf "ERROR: Error authenticating as user ${OPENAM_ADMIN} via REST.\n"
+  else
+    printf "INFO: Successfully authenicated as user ${OPENAM_ADMIN} via REST.\n"
+  fi
+}
+
+#---------------------------------------------
 # Main
 #---------------------------------------------
 checkSsoadm
+checkRestAuth
diff --git a/490-openam-uninstall b/490-openam-uninstall
--- a/490-openam-uninstall
+++ b/490-openam-uninstall
@@ -2,6 +2,7 @@
 
 . ./platform.properties
 . ./functions
+. ./functions-tomcat
 . ./functions-openam
 
 #---------------------------------------------
@@ -18,11 +19,22 @@ removeOpenAMFiles() {
 }
 
 #---------------------------------------------
+removeOpenAMWebApplication() {
+#---------------------------------------------
+  DEPLOY_DIR=${TOMCAT_WEBAPPS_DIR}/${OPENAM_DEPLOYMENT_URI}
+  if [ ! -z ${DEPLOY_DIR} ]; then
+    ${RM} -rf ${DEPLOY_DIR}
+    if [ $? != 0 ]; then
+      printf "ERROR: Error removing OpenAM web application from Tomcat (base directory is ${DEPLOY_DIR}). Aborting.\n"
+    else
+      printf "INFO: Successfully removed OpenAM web application from Tomcat.\n"
+    fi 
+  fi
+}
+
+#---------------------------------------------
 # Main
 #---------------------------------------------
+removeOpenAMWebApplication
 removeOpenAMFiles
-
-
-
-
 
