Use files in tmp section to build the json payload

diff --git a/621-deviceid b/621-deviceid
--- a/621-deviceid
+++ b/621-deviceid
@@ -5,7 +5,7 @@
 . ./functions-openam
 
 #---------------------------------------------
-checkRestAuthCallbacks() {
+authDeviceIdChainRestCallbacks() {
 #---------------------------------------------
   USER=$1
   PASSWORD=$2
@@ -21,19 +21,23 @@ checkRestAuthCallbacks() {
   printf "=============================================================\n"
   printf "INFO: [Step 1] Get authentication callbacks and JWT Token ...\n"
   printf "=============================================================\n"
-  #CURL_CMD1="${CURL} -s --insecure --request POST --header \"Content-Type: application/json\" ${REST_AUTH_URL}"
-  #printf "INFO: [Request] ${CURL_CMD}\n"dd
-  #RES1=`${CURL_CMD1}`
+  printf "INFO: [Request-URL] ${REST_AUTH_URL}\n"
+  printf "INFO: [Request-JSON] <empty>\n"
   RES1=`${CURL} -s --insecure --request POST --header \"Content-Type: application/json\" ${REST_AUTH_URL}`
   RC=$?
   if [ ${RC} != 0 ]; then
-    printf "ERROR: ssoadm returned ${RC}.\n"
+    printf "ERROR: curl returned ${RC}.\n"
     exit 1
   else
     printf "INFO: [Response] ${RES1}\n"
   fi
   JWT_TOKEN=`echo ${RES1} | /opt/misc/jq --raw-output '.authId'`
-  printf "INFO: JWT token is ${JWT_TOKEN}\n"
+  if [ ! -z ${JWT_TOKEN} ] && [ ${JWT_TOKEN} != "null" ]; then
+    printf "INFO: JWT token is ${JWT_TOKEN}\n"
+  else
+    printf "ERROR: JWT token is null. Authentication could not start.\n"
+    exit 1
+  fi
 
   # --------------------------------------------------------------------------------
   #
@@ -43,17 +47,20 @@ checkRestAuthCallbacks() {
   printf "=============================================================\n"
   printf "INFO: [Step 2] Authentication via REST (callbacks) as ${USER} ...\n"
   printf "=============================================================\n"
-  #Working with module DataStore  
-  RES2=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "DataStore1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "'${USER}'" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "changeit" } ] } ] }' ${REST_AUTH_URL}`
+  #Using module DataStore
+  #Build the json payload and write to a file
+  echo '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "DataStore1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "'${USER}'" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "'${PASSWORD}'" } ] } ] }' > ${TMP_BASE}/callback-deviceid-step2.json
+  printf "INFO: [Request-URL] ${REST_AUTH_URL}\n"
+  printf "INFO: [Request-JSON] `cat ${TMP_BASE}/callback-deviceid-step2.json`\n"
+
+  RES2=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data @${TMP_BASE}/callback-deviceid-step2.json ${REST_AUTH_URL}`
   RC=$?
   if [ ${RC} != 0 ]; then
-    printf "ERROR: ssoadm returned ${RC}.\n"
+    printf "ERROR: curl returned ${RC}.\n"
     exit 1
   else
     printf "INFO: [Response] ${RES2}\n"
   fi
-
-  printf "\n"
 
   # --------------------------------------------------------------------------------
   #
@@ -63,16 +70,17 @@ checkRestAuthCallbacks() {
   printf "=============================================================\n"
   printf "INFO: [Step 3] Provide callbacks for the DeviceId (Match) module ...\n"
   printf "=============================================================\n"
+  #Using module DeviceId (Match)
+  #Build the json payload and write to a file
+  ${SED} -e "s/%AUTHID%/${JWT_TOKEN}/g" templates/callback-deviceprint.json.TEMPLATE > ${TMP_BASE}/callback-deviceid-step3.json
+  printf "INFO: [Request-URL] ${REST_AUTH_URL}\n"
+  printf "INFO: [Request-JSON] `cat ${TMP_BASE}/callback-deviceid-step3.json`\n"
 
-  # Generate the device fingerprint data (e.g. from a template)
-  ${SED} -e "s/%AUTHID%/${JWT_TOKEN}/g" templates/deviceprint.json.TEMPLATE > deviceprint.json
-
-  # Working with scripted module
-  RES3=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data @deviceprint.json "${REST_AUTH_URL}"`
+  RES3=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data @${TMP_BASE}/callback-deviceid-step3.json "${REST_AUTH_URL}"`
 
   RC=$?
   if [ ${RC} != 0 ]; then
-    printf "ERROR: ssoadm returned ${RC}.\n"
+    printf "ERROR: curl returned ${RC}.\n"
     exit 1
   else
     printf "INFO: [Response] ${RES3}\n"
@@ -93,14 +101,20 @@ checkRestAuthCallbacks() {
   #
   # --------------------------------------------------------------------------------
   printf "=============================================================\n"
-  printf "INFO: [Step 4] Authentication via REST (callbacks) as ${USER} ...\n"
+  printf "INFO: [Step 4] Provide callbacks for the LDAP module ...\n"
   printf "=============================================================\n"
   #Working with module LDAP
-  RES4=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "LDAP1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "'${USER}'" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "'${PASSWORD}'" } ] } ] }' ${REST_AUTH_URL}`
+  #Build the json payload and write to a file
+  
+  echo '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "LDAP1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "'${USER}'" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "'${PASSWORD}'" } ] } ] }' > ${TMP_BASE}/callback-deviceid-step4.json
+  printf "INFO: [Request-URL] ${REST_AUTH_URL}\n"
+  printf "INFO: [Request-JSON] `cat ${TMP_BASE}/callback-deviceid-step4.json`\n"
+
+  RES4=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data @${TMP_BASE}/callback-deviceid-step4.json ${REST_AUTH_URL}`
 
   RC=$?
   if [ ${RC} != 0 ]; then
-    printf "ERROR: ssoadm returned ${RC}.\n"
+    printf "ERROR: curl returned ${RC}.\n"
     exit 1
   else
     printf "INFO: [Response] ${RES4}\n"
@@ -126,14 +140,17 @@ checkRestAuthCallbacks() {
   #
   # --------------------------------------------------------------------------------
   printf "=============================================================\n"
-  printf "INFO: [Step 5] Consent to store the trusted device information  ...\n"
+  printf "INFO: [Step 5] Provide callbacks for DeviceId (Save): Consent to store the trusted device information ...\n"
   printf "=============================================================\n"
-  #Working with module LDAP
-  RES5=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "DeviceSave2", "callbacks": [ { "type": "ChoiceCallback", "input": [ { "name": "IDToken1", "value": "1" } ] } ] }' ${REST_AUTH_URL}`
+  #Working with module DeviceId (Save)
+  echo '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "DeviceSave2", "callbacks": [ { "type": "ChoiceCallback", "input": [ { "name": "IDToken1", "value": "0" } ] } ] }' > ${TMP_BASE}/callback-deviceid-step5.json
+  printf "INFO: [Request-URL] ${REST_AUTH_URL}\n"
+  printf "INFO: [Request-JSON] `cat ${TMP_BASE}/callback-deviceid-step5.json`\n"
+  RES5=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data @${TMP_BASE}/callback-deviceid-step5.json ${REST_AUTH_URL}`
 
   RC=$?
   if [ ${RC} != 0 ]; then
-    printf "ERROR: ssoadm returned ${RC}.\n"
+    printf "ERROR: curl returned ${RC}.\n"
     exit 1
   else
     printf "INFO: [Response] ${RES5}\n"
@@ -146,13 +163,44 @@ checkRestAuthCallbacks() {
   else
     CALLBACKS=`echo ${RES5} | /opt/misc/jq --raw-output '.callbacks'`
     if [ ! -z "${CALLBACKS}" ] && [ "${CALLBACKS}" != "null" ]; then
-      printf "INFO: Callbacks returned. Assuming this is to get consent to store the device permanently.\n"
+      printf "INFO: Callbacks returned. Assuming this is to get the name under which the device should be stored.\n"
     else
       printf "INFO: Authentication failed.\n"
       exit 1
-    fi		
+    fi
   fi
 
+  # --------------------------------------------------------------------------------
+  #
+  # Sixth send the name under which the device profile shall be stored
+  #
+  # --------------------------------------------------------------------------------
+  printf "=============================================================\n"
+  printf "INFO: [Step 6] Provide the name under which the device profile shall be stored  ...\n"
+  printf "=============================================================\n"
+  #Working with module DeviceId (Save)
+  #If the device name is empty (value=""), il will be generated
+  echo '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "DeviceIdSave3", "callbacks": [ { "type": "NameCallback", "input": [ { "name": "IDToken1", "value": "" } ] } ] }' > ${TMP_BASE}/callback-deviceid-step6.json
+  printf "INFO: [Request-URL] ${REST_AUTH_URL}\n"
+  printf "INFO: [Request-JSON] `cat ${TMP_BASE}/callback-deviceid-step6.json`\n"
+  RES6=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data @${TMP_BASE}/callback-deviceid-step6.json ${REST_AUTH_URL}`
+
+  RC=$?
+  if [ ${RC} != 0 ]; then
+    printf "ERROR: curl returned ${RC}.\n"
+    exit 1
+  else
+    printf "INFO: [Response] ${RES5}\n"
+  fi
+  SSO_TOKEN=`echo ${RES6} | /opt/misc/jq --raw-output '.tokenId'`
+  if [ ! -z ${SSO_TOKEN} ] && [ ${SSO_TOKEN} != "null" ]; then
+    printf "INFO: Authentication successful.\n"
+    printf "INFO: SSO token is ${SSO_TOKEN}\n"
+    exit 0
+  else
+    printf "INFO: Authentication failed.\n"
+    exit 1
+  fi
 }
 
 #---------------------------------------------
@@ -169,7 +217,7 @@ authLDAP() {
   RES1=`${CURL} -s --insecure --request POST --header \"Content-Type: application/json\" ${REST_AUTH_URL}`
   RC=$?
   if [ ${RC} != 0 ]; then
-    printf "ERROR: ssoadm returned ${RC}.\n"
+    printf "ERROR: curl returned ${RC}.\n"
     exit 1
   else
     printf "INFO: [Response] ${RES1}\n"
@@ -181,11 +229,11 @@ authLDAP() {
   printf "INFO: Authentication via REST (callbacks) as ${USER} against realm ${OPENAM_DEVICEID_REALM} and module LDAP...\n"
   printf "=============================================================\n"
   #Working with module LDAP
-  RES4=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "LDAP1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "demo" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "'${PASSWORD}'" } ] } ] }' ${REST_AUTH_URL}`
+  RES4=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "LDAP1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "'${USER}'" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "'${PASSWORD}'" } ] } ] }' ${REST_AUTH_URL}`
 
   RC=$?
   if [ ${RC} != 0 ]; then
-    printf "ERROR: ssoadm returned ${RC}.\n"
+    printf "ERROR: curl returned ${RC}.\n"
     exit 1
   else
     printf "INFO: [Response] ${RES4}\n"
@@ -197,6 +245,6 @@ authLDAP() {
 #---------------------------------------------
 # Main
 #---------------------------------------------
-checkRestAuthCallbacks demo changeit
+authDeviceIdChainRestCallbacks demo changeit
 #authLDAP
 
