Cleanup 652 script

diff --git a/652-authz-create-policy b/652-authz-create-policy
--- a/652-authz-create-policy
+++ b/652-authz-create-policy
@@ -4,6 +4,8 @@
 . ./functions
 . ./functions-openam
 
+. ./651-authz-base
+
 #---------------------------------------------
 getResourceTypeUUID() {
 #---------------------------------------------
@@ -20,38 +22,6 @@ getResourceTypeUUID() {
 }
 
 #---------------------------------------------
-authUser() {
-#---------------------------------------------
-  USER=$1
-  PASSWORD=$2
-  REALM=$3
-
-  REST_AUTH_URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/authenticate?realm=${REALM}&_prettyPrint=true"
-
-  RES1=`${CURL} -s --insecure --request POST --header "X-OpenAM-Username: ${USER}" --header "X-OpenAM-Password: ${PASSWORD}" --header "Content-Type: application/json" --data "{}" "${REST_AUTH_URL}"`
-  RC=$?
-
-  if [ ${RC} != 0 ]; then
-    return 1
-  fi
- 
-  SSO_TOKEN=`echo ${RES1} | /opt/misc/jq --raw-output '.tokenId'`
-  if [ ! -z ${SSO_TOKEN} ] && [ ${SSO_TOKEN} != "null" ]; then
-    echo ${SSO_TOKEN}
-    return 0
-  else
-    return 1
-  fi
-}
-
-#---------------------------------------------
-authAdmin() {
-#---------------------------------------------
-  # Authenticate the admin against the root realm (rather than a sub realm)
-  authUser ${OPENAM_ADMIN} ${OPENAM_ADMIN_PASSWORD} ${OPENAM_ROOT_REALM}
-}
-
-#---------------------------------------------
 listResourceTypes() {
 #---------------------------------------------
   USER=$1
@@ -59,6 +29,10 @@ listResourceTypes() {
   REALM=$3
 
   SSO_TOKEN=`authAdmin`
+  if [ -z "${SSO_TOKEN}" ]; then
+    printf "ERROR: Admin SSO token is null. Admin authentication must have failed. Aborting.\n"
+    exit 1
+  fi
 
   URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/${REALM}/resourcetypes/?_queryFilter=true&_prettyPrint=true"
   RES=`${CURL} -s --insecure --request GET --header "iPlanetDirectoryPro: ${SSO_TOKEN}" "${URL}"`
@@ -80,6 +54,10 @@ importResourceType() {
   FILE=$2
 
   SSO_TOKEN=`authAdmin`
+  if [ -z "${SSO_TOKEN}" ]; then
+    printf "ERROR: Admin SSO token is null. Admin authentication must have failed. Aborting.\n"
+    exit 1
+  fi
 
   REST_RESOURCETYPES_URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/${REALM}/resourcetypes?_action=create&_prettyPrint=true"
   printf "INFO: Importing resource type from file ${FILE} ...\n"
@@ -104,6 +82,10 @@ importPolicy() {
   FILE=$2
 
   SSO_TOKEN=`authAdmin`
+  if [ -z "${SSO_TOKEN}" ]; then
+    printf "ERROR: Admin SSO token is null. Admin authentication must have failed. Aborting.\n"
+    exit 1
+  fi
 
   REST_POLICIES_URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/${REALM}/policies?_action=create&_prettyPrint=true"
   printf "INFO: Importing policy from file ${FILE} ...\n"
@@ -128,25 +110,6 @@ createSmartHomePolicies() {
   USER=$1
   PASSWORD=$2
   REALM=$3
-
-  # --------------------------------------------------------------------------------
-  #
-  # Third send in the credentials as required by the DeviceID (Match)
-  #
-  # --------------------------------------------------------------------------------
-  #printf "=============================================================\n"
-  #printf "INFO: [Step 3] Provide callbacks for the DeviceId (Match) module ...\n"
-  #printf "=============================================================\n"
-  #Using module DeviceId (Match)
-  #Build the json payload and write to a file
-  #${SED} -e "s/%AUTHID%/${JWT_TOKEN}/g" -e "s/%TELEPHONENUMBER%/${TELEPHONENUMBER}/g" ${DEVICEPRINT_CALLBACK_FILE} > ${TMP_BASE}/callback-deviceid-step3.json
-  #printf "INFO: [Request-URL] ${REST_AUTH_URL}\n"
-  #printf "INFO: [Request-JSON] `cat ${TMP_BASE}/callback-deviceid-step3.json`\n"
-
-  #RES3=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data @${TMP_BASE}/callback-deviceid-step3.json "${REST_AUTH_URL}"`
-
-  #RC=$?
-
 
   # --------------------------------------------------------------------------------
   #
@@ -185,40 +148,15 @@ createSmartHomePolicies() {
   # Create resource types
   #
   # --------------------------------------------------------------------------------
-  #REST_RESOURCETYPES_URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/${REALM}/resourcetypes?_action=create&_prettyPrint=true"
   printf "=============================================================\n"
   printf "INFO: [Step 2-1] Creating the resource type doorlock ...\n"
   printf "=============================================================\n"
-  #printf "INFO: [Request-URL] ${REST_RESOURCETYPES_URL}\n"
-  #printf "INFO: [Request-JSON] `cat templates/authz-resourcetypes-smarthome-doorlock.json`\n"
   importResourceType ${REALM} templates/authz-resourcetypes-smarthome-doorlock.json
-
-  #RES2=`${CURL} -s --insecure --request POST --header "iPlanetDirectoryPro: ${SSO_TOKEN}" --header "Content-Type: application/json" --data @templates/authz-resourcetypes-smarthome-doorlock.json "${REST_RESOURCETYPES_URL}"`
-  #RC=$?
-
-  #if [ ${RC} != 0 ]; then
-  #  printf "ERROR: curl returned ${RC}.\n"
-  #  return 1
-  #else
-  #  printf "INFO: [Response] ${RES2}\n"
-  #fi
 
   printf "=============================================================\n"
   printf "INFO: [Step 2-2] Creating the resource type TV ...\n"
   printf "=============================================================\n"
-  #printf "INFO: [Request-URL] ${REST_RESOURCETYPES_URL}\n"
-  #printf "INFO: [Request-JSON] `cat templates/authz-resourcetypes-smarthome-tv.json`\n"
   importResourceType ${REALM} templates/authz-resourcetypes-smarthome-tv.json
-
-  #RES3=`${CURL} -s --insecure --request POST --header "iPlanetDirectoryPro: ${SSO_TOKEN}" --header "Content-Type: application/json" --data @templates/authz-resourcetypes-smarthome-tv.json "${REST_RESOURCETYPES_URL}"`
-  #RC=$?
-
-  #if [ ${RC} != 0 ]; then
-  #  printf "ERROR: curl returned ${RC}.\n"
-  #  return 1
-  #else
-  #  printf "INFO: [Response] ${RES3}\n"
-  #fi
 
   printf "=============================================================\n"
   printf "INFO: [Step 2-3] Creating the resource type refrigerator ...\n"
@@ -237,7 +175,7 @@ createSmartHomePolicies() {
   # --------------------------------------------------------------------------------
   REST_APPLICATIONS_URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/${REALM}/applications?_action=create&_prettyPrint=true"
   printf "=============================================================\n"
-  printf "INFO: [Step 4] Creating the application (resource set) ...\n"
+  printf "INFO: [Step 3] Creating the application (resource set) ...\n"
   printf "=============================================================\n"
   #
   # Get the UUIDs of the resource sets
@@ -267,52 +205,27 @@ createSmartHomePolicies() {
 
   # --------------------------------------------------------------------------------
   #
-  # Create a policy
+  # Create policies
   #
   # --------------------------------------------------------------------------------
-  #REST_POLICIES_URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/${REALM}/policies?_action=create&_prettyPrint=true"
-
-  #URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/policies?_queryFilter=true&_prettyPrint=true"
-  #RES=`${CURL} -s --insecure --request GET --header "iPlanetDirectoryPro: ${SSO_TOKEN}" --header "Content-Type: application/json" "${URL}"`
-  #printf "INFO: [Response] ${RES}\n"
-  #
-  # Get the UUIDs of the resource sets
-  #
-  #UUID_DOORLOCK=`getResourceTypeUUID doorlock ${REALM} ${SSO_TOKEN}`
-  #UUID_TV=`getResourceTypeUUID tv ${REALM} ${SSO_TOKEN}`
-  #printf "INFO: UUID_DOORLOCK=${UUID_DOORLOCK}\n"
-  #printf "INFO: UUID_TV=${UUID_TV}\n"
-
   printf "=============================================================\n"
-  printf "INFO: [Step 5-1] Creating a policy for doorlock ...\n"
+  printf "INFO: [Step 4-1] Creating a policy for doorlock ...\n"
   printf "=============================================================\n"
-  ${SED} -e "s/%AUTHZ_RESOURCE_TYPE_DOORLOCK%/${UUID_DOORLOCK}/g" -e "s/%AUTHZ_POLICY_SET%/SmartHome/g" templates/authz-policy-smarthome-frontdoor.json.TEMPLATE > ${TMP_BASE}/authz-policy-smarthome-frontdoor.json
+  ${SED} -e "s/%AUTHZ_RESOURCE_TYPE_DOORLOCK%/${UUID_DOORLOCK}/g" -e "s/%AUTHZ_POLICY_SET%/${OPENAM_AUTHZ_RESOURCESET_SMARTHOME}/g" templates/authz-policy-smarthome-frontdoor.json.TEMPLATE > ${TMP_BASE}/authz-policy-smarthome-frontdoor.json
   importPolicy ${REALM} ${TMP_BASE}/authz-policy-smarthome-frontdoor.json
 
   printf "=============================================================\n"
-  printf "INFO: [Step 5-2] Creating a policy for homecinema ...\n"
+  printf "INFO: [Step 4-2] Creating a policy for homecinema ...\n"
   printf "=============================================================\n"
-  ${SED} -e "s/%AUTHZ_RESOURCE_TYPE_TV%/${UUID_TV}/g" -e "s/%AUTHZ_POLICY_SET%/SmartHome/g" templates/authz-policy-smarthome-homecinema.json.TEMPLATE > ${TMP_BASE}/authz-policy-smarthome-homecinema.json
+  ${SED} -e "s/%AUTHZ_RESOURCE_TYPE_TV%/${UUID_TV}/g" -e "s/%AUTHZ_POLICY_SET%/${OPENAM_AUTHZ_RESOURCESET_SMARTHOME}/g" templates/authz-policy-smarthome-homecinema.json.TEMPLATE > ${TMP_BASE}/authz-policy-smarthome-homecinema.json
   importPolicy ${REALM} ${TMP_BASE}/authz-policy-smarthome-homecinema.json
 
   printf "=============================================================\n"
-  printf "INFO: [Step 5-3] Creating a policy for winecabinet ...\n"
+  printf "INFO: [Step 4-3] Creating a policy for winecabinet ...\n"
   printf "=============================================================\n"
-  ${SED} -e "s/%AUTHZ_RESOURCE_TYPE_WINECABINET%/${UUID_WINECABINET}/g" -e "s/%AUTHZ_POLICY_SET%/SmartHome/g" templates/authz-policy-smarthome-winecabinet.json.TEMPLATE > ${TMP_BASE}/authz-policy-smarthome-winecabinet.json
+  ${SED} -e "s/%AUTHZ_RESOURCE_TYPE_WINECABINET%/${UUID_WINECABINET}/g" -e "s/%AUTHZ_POLICY_SET%/${OPENAM_AUTHZ_RESOURCESET_SMARTHOME}/g" templates/authz-policy-smarthome-winecabinet.json.TEMPLATE > ${TMP_BASE}/authz-policy-smarthome-winecabinet.json
   importPolicy ${REALM} ${TMP_BASE}/authz-policy-smarthome-winecabinet.json
 
-  #printf "INFO: [Request-URL] ${REST_POLICIES_URL}\n"
-  #printf "INFO: [Request-JSON] `cat ${TMP_BASE}/authz-policy-smarthome-frontdoor.json`\n"
-
-  #RES5=`${CURL} -s --insecure --request POST --header "iPlanetDirectoryPro: ${SSO_TOKEN}" --header "Content-Type: application/json" --data @${TMP_BASE}/authz-policy-smarthome-frontdoor.json "${REST_POLICIES_URL}"`
-  #RC=$?
-
-  #if [ ${RC} != 0 ]; then
-  #  printf "ERROR: curl returned ${RC}.\n"
-  #  return 1
-  #else
-  #  printf "INFO: [Response] ${RES5}\n"
-  #fi
 }
 
 #---------------------------------------------
